<header>
    <div class="grid_header">
        <div class="header_heading">
            <h1>Welcome to Dream Team IT Solutions</h1>
        </div>
        <div class="header_navbar">
            <nav>
                    <a href = "index.html">Home Page</a> 
                    <a href = "jobs.html">Jobs</a> 
                    <a href = "about.html">About Us</a> 
                    <a href="apply.html">Apply</a>
            </nav>
        </div>
    </div>
</header>