<header>
    <div class="grid_header">

        <div class="header_top">
            <div class="header_logo">
                    <img src="images/logo_transparent.png" alt="Company Logo">
            </div>
            <div class="header_heading">
                <h1>Welcome to Dream Team IT Solutions</h1>
            </div>
            <div class="header_contact">
                <a href="mailto:105871858@student.swin.edu.au">Email Us</a>
            </div>
            <div class="header_navbar">
                <nav>
                        <a href = "index.php">Home Page</a> 
                        <a href = "jobs.php">Jobs</a> 
                        <a href = "about.php">About Us</a> 
                        <a href="apply.php">Apply</a>
                </nav>
            </div>
        </div?
    </div>
    
</header>