<header>
    <div class="header_top">
        <div class="header_logo">
                <img src="../project2/styles/images/logo_transparent.png" alt="Company Logo">
        </div>

        <div class="header_center">
            <div class="header_heading">
                <h1>Welcome to Dream Team IT Solutions</h1>
            </div>
        
            <?php include("header.inc"); ?>
        </div>
    </div>
    
</header>